name: PDFScanner-MTA

channels:
- conda-forge
- defaults

dependencies:
- python=3.10
- pip
- poppler
- pdf2image
- flask
- pytesseract
- tesseract
- pathlib
- Werkzeug~=2.2.2
- pip:
  - -r requirements.txt